version: "3"

services:
  nginx:
    image: nginx:stable
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  processes:
    build: processes-api/.
    depends_on:
      - nginx
    environment:
      - SCRIPT_NAME=/api
    volumes:
      - ./processes-api/config.yml:/pygeoapi/local.config.yml
      - ./processes-api/data/test.geojson:/pygeoapi/data/test.geojson
      - ./processes-api/model1/:/pygeoapi/pygeoapi/process/
      - ./processes-api/plugin.py:/pygeoapi/pygeoapi/plugin.py

  api:
    build: api/.
    environment:
      - LOGLEVEL=DEBUG
      - FLASK_DEBUG=True
      - POSTGRES_USER=cut_re3
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cut_re3_dev
    ports:
      - 5001:5001
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - db

  frontend:
    build: frontend/.
    working_dir: /home/node/workspace
    user: node
    command: "npm start"
    depends_on:
      - nginx
    volumes:
      - ./frontend:/home/node/workspace
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data:delegated
      - ./api/initializers/db:/docker-entrypoint-initdb.d:delegated
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cut_re3_dev
